modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mixins]]
config = "frontutil.mixins.json"

[[mods]]
modId = "frontutil"
version = "0.2.6"
displayName = "Front-Utilities"
description = '''Helper stuff for BlockFront'''
logoFile = "logo.png"
updateJSONURL = "https://raw.githubusercontent.com/forteus19/Front-Utilities/main/update.json"

[[dependencies.frontutil]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.215,22.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.frontutil]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.frontutil]]
modId = "bf"
type = "required"
versionRange = "[0.7.1.2b]"
ordering = "AFTER"
side = "BOTH"
